services:
  server:
    build: .
    container_name: server
    ports:
      - 80:80
    volumes:
      - ./app:/app
  
  database:
    image: mysql
    container_name: database
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password-123
    volumes:
      - database:/var/lib/mysql

volumes:
  database: